### ISSUE TITLE
Couldn't find either the add-on service or the add-on plan of "mongolab".

### ISSUE THREAD

**Issue by aquawill** [Keplerjs/kepler-skeleton#1]
Error message while deploying to heroku: Couldn't find either the add-on service or the add-on plan of "mongolab".

![chrome_kB1BzW9Ejq](https://user-images.githubusercontent.com/20334897/150748569-82cba984-0263-4df1-bf08-fa2b033e23dc.png)

**Comment by stefanocudini** [comment]
you can use any remote mongodb service
